"use client";

import React, { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  AlertTriangle,
  ShieldCheck,
  Zap,
  Clock,
  Navigation,
  Compass,
  ArrowRight,
  TrendingDown,
  Activity,
  CheckCircle2,
  RefreshCw,
  FileText,
  Radio,
  FileCode,
  Download,
  Copy,
  Check,
  X,
  Layers,
  Crosshair,
} from "lucide-react";
import { ConjunctionEvent, SpaceAsset } from "../../types/ssa";

interface ConjunctionsProps {
  conjunctions: ConjunctionEvent[];
  assets: SpaceAsset[];
  onSelectConjunction?: (event: ConjunctionEvent) => void;
  onExecuteManeuver: (conjunctionId: string) => void;
  isFocused?: boolean;
  theme?: "dark" | "light";
}

export const Conjunctions: React.FC<ConjunctionsProps> = ({
  conjunctions,
  assets,
  onSelectConjunction,
  onExecuteManeuver,
  isFocused = false,
  theme = "dark",
}) => {
  const [activeManeuverId, setActiveManeuverId] = useState<string | null>(null);
  const [telemetryLogs, setTelemetryLogs] = useState<{ [id: string]: string[] }>({});
  const [timeRemaining, setTimeRemaining] = useState<{ [id: string]: string }>({});
  const [detailedReportConj, setDetailedReportConj] = useState<ConjunctionEvent | null>(null);
  const [copiedTle, setCopiedTle] = useState<boolean>(false);

  useEffect(() => {
    const updateCountdowns = () => {
      const updated: { [id: string]: string } = {};
      const now = Date.now();

      conjunctions.forEach((conj) => {
        const tcaMs = new Date(conj.tca).getTime();
        const diffSec = Math.floor((tcaMs - now) / 1000);

        if (diffSec <= 0) {
          updated[conj.id] = "TCA PASSED";
        } else {
          const hours = Math.floor(diffSec / 3600);
          const minutes = Math.floor((diffSec % 3600) / 60);
          const seconds = diffSec % 60;
          updated[conj.id] = `T-${String(hours).padStart(2, "0")}:${String(minutes).padStart(
            2,
            "0"
          )}:${String(seconds).padStart(2, "0")}`;
        }
      });
      setTimeRemaining(updated);
    };

    updateCountdowns();
    const interval = setInterval(updateCountdowns, 1000);
    return () => clearInterval(interval);
  }, [conjunctions]);

  const handleComputeManeuver = (conjId: string) => {
    setActiveManeuverId(conjId);
    setTelemetryLogs((prev) => ({
      ...prev,
      [conjId]: [
        "[00:01] Ingesting radar tracking covariance matrix & 3-axis encounter state vectors...",
      ],
    }));

    setTimeout(() => {
      setTelemetryLogs((prev) => ({
        ...prev,
        [conjId]: [
          ...(prev[conjId] || []),
          "[00:02] Computing impulsive posigrade correction burn vector: ΔV = 0.65 m/s @ T-18m.",
        ],
      }));
    }, 600);

    setTimeout(() => {
      setTelemetryLogs((prev) => ({
        ...prev,
        [conjId]: [
          ...(prev[conjId] || []),
          "[00:03] Recalculating 2D encounter probability sphere: Miss distance expands to 6,420 m.",
          "[00:04] Collision probability Pc neutralized to nominal 1.0e-7 threshold.",
        ],
      }));
    }, 1300);
  };

  const getPrimaryAsset = (conj: ConjunctionEvent) => {
    return assets.find((a) => a.id === conj.primaryAssetId) || assets[0];
  };

  const getChaserAsset = (conj: ConjunctionEvent) => {
    return assets.find((a) => a.id === conj.chaserDebrisId) || assets[4] || assets[0];
  };

  const handleCopyReportTle = (primary: SpaceAsset, chaser: SpaceAsset) => {
    const text = `// PRIMARY OBJECT\n${primary.name}\n${primary.tleLine1}\n${primary.tleLine2}\n\n// CHASER OBJECT\n${chaser.name}\n${chaser.tleLine1}\n${chaser.tleLine2}`;
    navigator.clipboard.writeText(text);
    setCopiedTle(true);
    setTimeout(() => setCopiedTle(false), 2000);
  };

  const handleDownloadCdm = (conj: ConjunctionEvent, primary: SpaceAsset, chaser: SpaceAsset) => {
    const cdmData = `CCSDS_CDM_VERS = 1.0
COMMENT = "Authoritative Conjunction Data Message (CDM) generated by SSA4ALL Orbital Intelligence Lab"
CREATION_DATE = "${new Date().toISOString()}"
ORIGINATOR = "SSA4ALL // ORBITAL INTELLIGENCE LAB"
MESSAGE_ID = "${conj.id}"

TCA = "${conj.tca}"
MISS_DISTANCE = ${conj.missDistance.toFixed(2)} [m]
RADIAL_MISS_DISTANCE = ${conj.missDistanceRadial.toFixed(2)} [m]
IN_TRACK_MISS_DISTANCE = ${conj.missDistanceInTrack.toFixed(2)} [m]
CROSS_TRACK_MISS_DISTANCE = ${conj.missDistanceCrossTrack.toFixed(2)} [m]
RELATIVE_SPEED = ${conj.relativeVelocity.toFixed(4)} [km/s]
COLLISION_PROBABILITY = ${conj.pc.toExponential(4)}
SCREENING_VOLUME_RADIUS = 25000.0 [m]

OBJECT1_NAME = "${primary.name}"
OBJECT1_NORAD = ${primary.noradId}
OBJECT1_INCLINATION = ${primary.inclination} [deg]
OBJECT1_APOGEE = ${primary.apogee} [km]
OBJECT1_PERIGEE = ${primary.perigee} [km]
OBJECT1_TLE_LINE1 = "${primary.tleLine1}"
OBJECT1_TLE_LINE2 = "${primary.tleLine2}"

OBJECT2_NAME = "${chaser.name}"
OBJECT2_NORAD = ${chaser.noradId}
OBJECT2_INCLINATION = ${chaser.inclination} [deg]
OBJECT2_APOGEE = ${chaser.apogee} [km]
OBJECT2_PERIGEE = ${chaser.perigee} [km]
OBJECT2_TLE_LINE1 = "${chaser.tleLine1}"
OBJECT2_TLE_LINE2 = "${chaser.tleLine2}"
`;
    const blob = new Blob([cdmData], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `CDM_${conj.id}_CCSDS508.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div
      className={`orbit-panel rounded-2xl p-6 transition-all ${
        theme === "light"
          ? "bg-white border-purple-200 shadow-md text-purple-950"
          : "bg-[#140236] border-[rgba(75,20,140,0.7)] text-white"
      }`}
    >
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 pb-4 border-b border-purple-900/60 mb-5">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-orbit-crimson/20 border border-orbit-crimson/40">
            <AlertTriangle className="w-6 h-6 text-orbit-crimson glow-crimson animate-pulse" />
          </div>
          <div>
            <div className="font-display text-base font-black tracking-widest uppercase flex items-center gap-2">
              <span>CONJUNCTION ASSESSMENT & COLLISION AVOIDANCE</span>
              <span className="text-[11px] bg-orbit-crimson/20 border border-orbit-crimson/50 text-orbit-crimson px-2.5 py-0.5 rounded-lg font-mono font-bold">
                {conjunctions.filter((c) => c.riskLevel === "CRITICAL" && c.maneuverStatus !== "AVOIDED").length} CRITICAL CDMs
              </span>
            </div>
            <div className="text-xs opacity-75 font-sans mt-0.5">
              Automated Screening, 3D Covariance Propagation & Impulsive CAM Trajectories
            </div>
          </div>
        </div>
      </div>

      {/* Conjunction Cards List */}
      <div className="space-y-4">
        {conjunctions.map((conj) => {
          const isCritical = conj.riskLevel === "CRITICAL";
          const isAvoided = conj.maneuverStatus === "AVOIDED";
          const isCalculating = activeManeuverId === conj.id && !isAvoided;
          const primary = getPrimaryAsset(conj);
          const chaser = getChaserAsset(conj);

          return (
            <motion.div
              key={conj.id}
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              className={`p-5 rounded-2xl border transition-all ${
                isAvoided
                  ? "bg-emerald-950/20 border-emerald-500/40"
                  : isCritical
                  ? theme === "light"
                    ? "bg-red-50/80 border-orbit-crimson shadow-md"
                    : "bg-[#25032b] border-orbit-crimson/80 shadow-crimson-glow"
                  : theme === "light"
                  ? "bg-purple-50/40 border-purple-200"
                  : "bg-black/60 border-purple-950"
              }`}
            >
              <div className="flex flex-wrap items-center justify-between gap-3 pb-3 border-b border-purple-900/60">
                <div className="flex items-center gap-2.5">
                  <span
                    className={`w-3 h-3 rounded-full ${
                      isAvoided
                        ? "bg-emerald-400"
                        : isCritical
                        ? "bg-orbit-crimson animate-orange-pulse"
                        : "bg-orbit-orange"
                    }`}
                  />
                  <div className="font-display text-sm font-bold truncate">
                    <span>{conj.primaryAssetName}</span>
                    <span className="text-orbit-crimson mx-2">⚡</span>
                    <span className="text-slate-300">{conj.chaserDebrisName}</span>
                  </div>
                </div>

                <div className="flex items-center gap-3">
                  <div className="font-mono text-xs font-bold text-orbit-orange bg-black/60 px-3 py-1 rounded-lg border border-purple-900 flex items-center gap-1.5">
                    <Clock className="w-3.5 h-3.5" />
                    <span>{timeRemaining[conj.id] || "SYNCING..."}</span>
                  </div>

                  <button
                    onClick={() => setDetailedReportConj(conj)}
                    className="px-3 py-1 bg-black/80 hover:bg-purple-900 border border-purple-800 text-xs font-bold rounded-lg flex items-center gap-1.5 text-slate-200 transition-colors"
                    title="View Complete Conjunction Assessment & Orbits Report"
                  >
                    <FileText className="w-3.5 h-3.5 text-orbit-orange" />
                    <span>VIEW FULL REPORT</span>
                  </button>
                </div>
              </div>

              {/* Assessment Metrics Grid */}
              <div className="grid grid-cols-2 md:grid-cols-4 gap-3 my-4 font-mono text-xs">
                <div className="p-3 bg-black/50 rounded-xl border border-purple-900/60">
                  <div className="text-[10px] opacity-60 font-sans">MISS DISTANCE</div>
                  <div className={`text-base font-bold mt-0.5 ${isCritical && !isAvoided ? "text-orbit-crimson" : "text-white"}`}>
                    {conj.missDistance.toFixed(1)} m
                  </div>
                  <div className="text-[10px] opacity-50 mt-1">
                    R: {conj.missDistanceRadial.toFixed(0)}m | T: {conj.missDistanceInTrack.toFixed(0)}m
                  </div>
                </div>

                <div className="p-3 bg-black/50 rounded-xl border border-purple-900/60">
                  <div className="text-[10px] opacity-60 font-sans">COLLISION PROBABILITY (Pc)</div>
                  <div className={`text-base font-bold mt-0.5 ${isCritical && !isAvoided ? "text-orbit-crimson animate-pulse" : "text-emerald-400"}`}>
                    {conj.pc.toExponential(3)}
                  </div>
                  <div className="text-[10px] opacity-50 mt-1">FOSTER 3D INTEGRAL</div>
                </div>

                <div className="p-3 bg-black/50 rounded-xl border border-purple-900/60">
                  <div className="text-[10px] opacity-60 font-sans">RELATIVE VELOCITY</div>
                  <div className="text-base font-bold text-orbit-orange mt-0.5">
                    {conj.relativeVelocity.toFixed(2)} km/s
                  </div>
                  <div className="text-[10px] opacity-50 mt-1">CLOSING SPEED: {(conj.relativeVelocity * 3600).toFixed(0)} km/h</div>
                </div>

                <div className="p-3 bg-black/50 rounded-xl border border-purple-900/60">
                  <div className="text-[10px] opacity-60 font-sans">AVOIDANCE STATUS</div>
                  <div className={`text-sm font-bold mt-0.5 ${isAvoided ? "text-emerald-400" : "text-orbit-orange"}`}>
                    {isAvoided ? "COLLISION AVOIDED" : "MANEUVER REQUIRED"}
                  </div>
                  <div className="text-[10px] opacity-50 mt-1">REQ ΔV: {conj.requiredDeltaV || 0.65} m/s</div>
                </div>
              </div>

              {/* Action Maneuver Controls */}
              {!isAvoided && isCritical && (
                <div className="flex flex-wrap items-center justify-between gap-3 pt-2">
                  <div className="text-xs font-sans opacity-80">
                    Calculated optimal burn epoch: <strong>T-24m</strong> at anti-velocity vector to raise perigee by +4.2km.
                  </div>

                  <div className="flex items-center gap-2">
                    <button
                      onClick={() => handleComputeManeuver(conj.id)}
                      disabled={isCalculating}
                      className="px-3.5 py-2 rounded-xl bg-purple-900/70 hover:bg-purple-800 border border-purple-600 text-white text-xs font-bold transition-all flex items-center gap-1.5"
                    >
                      <RefreshCw className={`w-3.5 h-3.5 ${isCalculating ? "animate-spin" : ""}`} />
                      <span>{isCalculating ? "OPTIMIZING TRAJECTORY..." : "CALCULATE MANEUVER"}</span>
                    </button>

                    <button
                      onClick={() => onExecuteManeuver(conj.id)}
                      className="px-4 py-2 rounded-xl bg-orbit-orange text-white hover:bg-orbit-orangeBright text-xs font-black shadow-orange-glow transition-all flex items-center gap-1.5 uppercase tracking-wider"
                    >
                      <Zap className="w-3.5 h-3.5" />
                      <span>EXECUTE COLLISION AVOIDANCE</span>
                    </button>
                  </div>
                </div>
              )}

              {/* Telemetry Output Logs */}
              {telemetryLogs[conj.id] && (
                <div className="mt-3 p-3 bg-black rounded-xl border border-purple-900/70 font-mono text-[11px] text-slate-300 space-y-1">
                  {telemetryLogs[conj.id].map((log, i) => (
                    <div key={i} className="text-emerald-400">
                      {log}
                    </div>
                  ))}
                </div>
              )}
            </motion.div>
          );
        })}
      </div>

      {/* FULL DETAILED CONJUNCTION ASSESSMENT & ORBITS REPORT MODAL */}
      <AnimatePresence>
        {detailedReportConj && (() => {
          const primary = getPrimaryAsset(detailedReportConj);
          const chaser = getChaserAsset(detailedReportConj);

          return (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 bg-black/80 backdrop-blur-md z-50 flex items-center justify-center p-4"
            >
              <motion.div
                initial={{ scale: 0.92, y: 15 }}
                animate={{ scale: 1, y: 0 }}
                exit={{ scale: 0.92, y: 15 }}
                className={`max-w-4xl w-full max-h-[90vh] overflow-y-auto rounded-3xl p-6 sm:p-8 border shadow-2xl space-y-6 ${
                  theme === "light"
                    ? "bg-white border-purple-200 text-purple-950"
                    : "bg-[#140236] border-purple-700 text-white"
                }`}
              >
                {/* Header */}
                <div className="flex items-center justify-between pb-4 border-b border-purple-900/60">
                  <div className="flex items-center gap-3">
                    <div className="p-2.5 rounded-2xl bg-orbit-crimson/20 border border-orbit-crimson/40">
                      <ShieldCheck className="w-7 h-7 text-orbit-crimson" />
                    </div>
                    <div>
                      <h3 className="font-display text-base sm:text-lg font-black uppercase text-orbit-orange">
                        DETAILED CONJUNCTION ASSESSMENT REPORT // {detailedReportConj.id}
                      </h3>
                      <p className="text-xs opacity-75 font-sans">
                        Authoritative Flight Dynamics Screening, 3D Covariance Ellipsoids & TLE Data
                      </p>
                    </div>
                  </div>
                  <button
                    onClick={() => setDetailedReportConj(null)}
                    className="p-2 rounded-xl text-slate-400 hover:text-white"
                  >
                    <X className="w-6 h-6" />
                  </button>
                </div>

                {/* Section 1: Encounter Geometry & Risk Assessment */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 font-mono text-xs">
                  <div className="p-3.5 bg-black/60 rounded-xl border border-purple-900">
                    <div className="text-[10px] opacity-60 font-sans">TCA (TIME OF CLOSEST APPROACH)</div>
                    <div className="text-sm font-bold text-orbit-orange mt-1">{new Date(detailedReportConj.tca).toUTCString()}</div>
                  </div>
                  <div className="p-3.5 bg-black/60 rounded-xl border border-purple-900">
                    <div className="text-[10px] opacity-60 font-sans">OVERALL MISS DISTANCE</div>
                    <div className="text-sm font-bold text-orbit-crimson mt-1">{detailedReportConj.missDistance.toFixed(2)} meters</div>
                  </div>
                  <div className="p-3.5 bg-black/60 rounded-xl border border-purple-900">
                    <div className="text-[10px] opacity-60 font-sans">COLLISION PROBABILITY (Pc)</div>
                    <div className="text-sm font-bold text-orbit-crimson mt-1">{detailedReportConj.pc.toExponential(4)}</div>
                  </div>
                  <div className="p-3.5 bg-black/60 rounded-xl border border-purple-900">
                    <div className="text-[10px] opacity-60 font-sans">RELATIVE VELOCITY</div>
                    <div className="text-sm font-bold text-white mt-1">{detailedReportConj.relativeVelocity.toFixed(3)} km/s</div>
                  </div>
                </div>

                {/* Section 2: Conjunction Orbits Side-by-Side Comparison */}
                <div className="space-y-2">
                  <div className="font-display text-xs font-bold text-orbit-orange uppercase tracking-wider flex items-center gap-2">
                    <Layers className="w-4 h-4 text-orbit-orange" />
                    <span>CONJUNCTION ORBITS SIDE-BY-SIDE PARAMETERS</span>
                  </div>

                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 font-mono text-xs">
                    {/* Primary Object Orbit */}
                    <div className="p-4 bg-black/70 rounded-2xl border border-purple-900 space-y-2.5">
                      <div className="flex items-center justify-between pb-2 border-b border-purple-900/60 font-bold">
                        <span className="text-orbit-orange font-sans">{primary.name}</span>
                        <span className="text-[10px] bg-purple-900/60 px-2 py-0.5 rounded text-purple-200">PRIMARY</span>
                      </div>
                      <div className="grid grid-cols-2 gap-x-2 gap-y-1.5 opacity-90 text-[11px]">
                        <div>NORAD ID: <strong>{primary.noradId}</strong></div>
                        <div>ORBIT CLASS: <strong>{primary.orbitClass}</strong></div>
                        <div>INCLINATION: <strong className="text-orbit-orange">{primary.inclination}°</strong></div>
                        <div>PERIOD: <strong>{primary.period} min</strong></div>
                        <div>APOGEE: <strong>{primary.apogee} km</strong></div>
                        <div>PERIGEE: <strong>{primary.perigee} km</strong></div>
                        <div>MASS: <strong>{primary.massKg.toLocaleString()} kg</strong></div>
                        <div>RCS: <strong>{primary.radarCrossSection} m²</strong></div>
                      </div>
                    </div>

                    {/* Chaser Debris Orbit */}
                    <div className="p-4 bg-black/70 rounded-2xl border border-purple-900 space-y-2.5">
                      <div className="flex items-center justify-between pb-2 border-b border-purple-900/60 font-bold">
                        <span className="text-orbit-crimson font-sans">{chaser.name}</span>
                        <span className="text-[10px] bg-orbit-crimson/20 text-orbit-crimson px-2 py-0.5 rounded">CHASER / DEBRIS</span>
                      </div>
                      <div className="grid grid-cols-2 gap-x-2 gap-y-1.5 opacity-90 text-[11px]">
                        <div>NORAD ID: <strong>{chaser.noradId}</strong></div>
                        <div>ORBIT CLASS: <strong>{chaser.orbitClass}</strong></div>
                        <div>INCLINATION: <strong className="text-orbit-crimson">{chaser.inclination}°</strong></div>
                        <div>PERIOD: <strong>{chaser.period} min</strong></div>
                        <div>APOGEE: <strong>{chaser.apogee} km</strong></div>
                        <div>PERIGEE: <strong>{chaser.perigee} km</strong></div>
                        <div>MASS: <strong>{chaser.massKg.toLocaleString()} kg</strong></div>
                        <div>RCS: <strong>{chaser.radarCrossSection} m²</strong></div>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Section 3: Two-Line Element (TLE) Data for Both Objects */}
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="font-display text-xs font-bold text-orbit-orange uppercase tracking-wider flex items-center gap-2">
                      <FileCode className="w-4 h-4 text-orbit-orange" />
                      <span>AUTHORITATIVE TLE DATA (PRIMARY & CHASER)</span>
                    </span>
                    <button
                      onClick={() => handleCopyReportTle(primary, chaser)}
                      className="px-2.5 py-1 rounded-lg bg-black border border-purple-800 text-[11px] font-mono flex items-center gap-1.5 text-slate-200 hover:text-white"
                    >
                      {copiedTle ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                      <span>{copiedTle ? "COPIED TLEs" : "COPY BOTH TLEs"}</span>
                    </button>
                  </div>

                  <div className="p-4 bg-black rounded-2xl border border-purple-900 font-mono text-xs space-y-3">
                    <div>
                      <div className="text-[11px] text-orbit-orange font-bold font-sans">{primary.name} // LINE 1 & 2</div>
                      <div className="text-slate-300 text-[11px] select-all">{primary.tleLine1}</div>
                      <div className="text-slate-300 text-[11px] select-all">{primary.tleLine2}</div>
                    </div>
                    <div className="pt-2 border-t border-purple-950">
                      <div className="text-[11px] text-orbit-crimson font-bold font-sans">{chaser.name} // LINE 1 & 2</div>
                      <div className="text-slate-300 text-[11px] select-all">{chaser.tleLine1}</div>
                      <div className="text-slate-300 text-[11px] select-all">{chaser.tleLine2}</div>
                    </div>
                  </div>
                </div>

                {/* Modal Footer Actions */}
                <div className="flex flex-wrap items-center justify-between gap-3 pt-3 border-t border-purple-900/60">
                  <button
                    onClick={() => handleDownloadCdm(detailedReportConj, primary, chaser)}
                    className="px-4 py-2.5 rounded-xl bg-purple-900/80 hover:bg-purple-800 border border-purple-600 text-white font-sans text-xs font-bold flex items-center gap-2 transition-colors"
                  >
                    <Download className="w-4 h-4 text-orbit-orange" />
                    <span>EXPORT CCSDS 508.0 CDM FILE</span>
                  </button>

                  <div className="flex items-center gap-3">
                    <button
                      onClick={() => setDetailedReportConj(null)}
                      className="px-4 py-2.5 rounded-xl border border-purple-800 text-xs font-bold font-sans hover:bg-white/10 transition-colors"
                    >
                      CLOSE REPORT
                    </button>
                    {detailedReportConj.riskLevel === "CRITICAL" && detailedReportConj.maneuverStatus !== "AVOIDED" && (
                      <button
                        onClick={() => {
                          onExecuteManeuver(detailedReportConj.id);
                          setDetailedReportConj(null);
                        }}
                        className="px-5 py-2.5 rounded-xl bg-orbit-orange text-white hover:bg-orbit-orangeBright text-xs font-black font-sans shadow-orange-glow flex items-center gap-2 uppercase tracking-wider transition-all"
                      >
                        <Zap className="w-4 h-4" />
                        <span>EXECUTE AVOIDANCE MANEUVER</span>
                      </button>
                    )}
                  </div>
                </div>
              </motion.div>
            </motion.div>
          );
        })()}
      </AnimatePresence>
    </div>
  );
};
